# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import federated_learning_pb2 as federated__learning__pb2

# Relax gRPC runtime requirement to match Python 3.8-compatible grpcio
GRPC_GENERATED_VERSION = '1.59.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
        from grpc._utilities import first_version_is_lower
        _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except Exception:
        # Older grpc releases may not expose _utilities; assume compatible
        _version_not_supported = False

# Disable strict runtime version gate to support Python 3.8-compatible grpcio
if False:
        raise RuntimeError(
                f'The grpc package installed is at version {GRPC_VERSION},'
                + ' but the generated code in federated_learning_pb2_grpc.py depends on'
                + f' grpcio>={GRPC_GENERATED_VERSION}.'
                + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
                + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        )


class FederatedLearningStub(object):
    """Service definition for Federated Learning
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterClient = channel.unary_unary(
                '/federated_learning.FederatedLearning/RegisterClient',
                request_serializer=federated__learning__pb2.ClientRegistration.SerializeToString,
                response_deserializer=federated__learning__pb2.RegistrationResponse.FromString)
        self.GetGlobalModel = channel.unary_unary(
                '/federated_learning.FederatedLearning/GetGlobalModel',
                request_serializer=federated__learning__pb2.ModelRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.GlobalModel.FromString)
        self.SendModelUpdate = channel.unary_unary(
                '/federated_learning.FederatedLearning/SendModelUpdate',
                request_serializer=federated__learning__pb2.ModelUpdate.SerializeToString,
                response_deserializer=federated__learning__pb2.UpdateResponse.FromString)
        self.SendMetrics = channel.unary_unary(
                '/federated_learning.FederatedLearning/SendMetrics',
                request_serializer=federated__learning__pb2.EvaluationMetrics.SerializeToString,
                response_deserializer=federated__learning__pb2.MetricsResponse.FromString)
        self.GetTrainingConfig = channel.unary_unary(
                '/federated_learning.FederatedLearning/GetTrainingConfig',
                request_serializer=federated__learning__pb2.ConfigRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.TrainingConfig.FromString)
        self.CheckTrainingStatus = channel.unary_unary(
                '/federated_learning.FederatedLearning/CheckTrainingStatus',
                request_serializer=federated__learning__pb2.StatusRequest.SerializeToString,
                response_deserializer=federated__learning__pb2.TrainingStatus.FromString)


class FederatedLearningServicer(object):
    """Service definition for Federated Learning
    """

    def RegisterClient(self, request, context):
        """Client registration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobalModel(self, request, context):
        """Server sends global model to client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendModelUpdate(self, request, context):
        """Client sends local model update to server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMetrics(self, request, context):
        """Client sends evaluation metrics to server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingConfig(self, request, context):
        """Get training configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckTrainingStatus(self, request, context):
        """Check if training should start for a round
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedLearningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=federated__learning__pb2.ClientRegistration.FromString,
                    response_serializer=federated__learning__pb2.RegistrationResponse.SerializeToString,
            ),
            'GetGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalModel,
                    request_deserializer=federated__learning__pb2.ModelRequest.FromString,
                    response_serializer=federated__learning__pb2.GlobalModel.SerializeToString,
            ),
            'SendModelUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendModelUpdate,
                    request_deserializer=federated__learning__pb2.ModelUpdate.FromString,
                    response_serializer=federated__learning__pb2.UpdateResponse.SerializeToString,
            ),
            'SendMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMetrics,
                    request_deserializer=federated__learning__pb2.EvaluationMetrics.FromString,
                    response_serializer=federated__learning__pb2.MetricsResponse.SerializeToString,
            ),
            'GetTrainingConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingConfig,
                    request_deserializer=federated__learning__pb2.ConfigRequest.FromString,
                    response_serializer=federated__learning__pb2.TrainingConfig.SerializeToString,
            ),
            'CheckTrainingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckTrainingStatus,
                    request_deserializer=federated__learning__pb2.StatusRequest.FromString,
                    response_serializer=federated__learning__pb2.TrainingStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federated_learning.FederatedLearning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    # Older grpcio versions (e.g., 1.59.x for Python 3.8) do not expose
    # server.add_registered_method_handlers. It's safe to skip this call
    # and rely on the generic handler registration above.
    try:
            server.add_registered_method_handlers('federated_learning.FederatedLearning', rpc_method_handlers)
    except AttributeError:
            pass


 # This class is part of an EXPERIMENTAL API.
class FederatedLearning(object):
    """Service definition for Federated Learning
    """

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
                return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.FederatedLearning/RegisterClient',
            federated__learning__pb2.ClientRegistration.SerializeToString,
            federated__learning__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
                        metadata)

    @staticmethod
    def GetGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
                return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.FederatedLearning/GetGlobalModel',
            federated__learning__pb2.ModelRequest.SerializeToString,
            federated__learning__pb2.GlobalModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
                        metadata)

    @staticmethod
    def SendModelUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
                return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.FederatedLearning/SendModelUpdate',
            federated__learning__pb2.ModelUpdate.SerializeToString,
            federated__learning__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
                        metadata)

    @staticmethod
    def SendMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
                return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.FederatedLearning/SendMetrics',
            federated__learning__pb2.EvaluationMetrics.SerializeToString,
            federated__learning__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
                        metadata)

    @staticmethod
    def GetTrainingConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.FederatedLearning/GetTrainingConfig',
            federated__learning__pb2.ConfigRequest.SerializeToString,
            federated__learning__pb2.TrainingConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckTrainingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated_learning.FederatedLearning/CheckTrainingStatus',
            federated__learning__pb2.StatusRequest.SerializeToString,
            federated__learning__pb2.TrainingStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
