#!/usr/bin/env bash

# ============================================================================
# DEPENDENCY FIX VERIFICATION & REBUILD COMMANDS
# ============================================================================
# Run these commands to verify the comprehensive dependency fix and
# rebuild all Docker images with proper dependency resolution.
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=../../scripts/lib/resolve_python.sh
source "$PROJECT_DIR/scripts/lib/resolve_python.sh" || exit 1

echo "==============================================="
echo "📋 DEPENDENCY FIX SUMMARY"
echo "==============================================="
echo ""
echo "✅ Fixed Issues:"
echo "  1. Added pytz (pandas timezone support)"
echo "  2. Added python-dateutil (pandas datetime support)"
echo "  3. Added Pillow (matplotlib image support)"
echo "  4. Removed --no-deps flag from pip (enables auto-dependency resolution)"
echo ""
echo "✅ Files Modified:"
echo "  - requirements.txt (added missing dependencies)"
echo "  - Server/Dockerfile (removed --no-deps)"
echo "  - Client/Dockerfile (removed --no-deps)"
echo ""
echo "==============================================="
echo "🔨 REBUILD ALL IMAGES"
echo "==============================================="
echo ""
echo "# Option 1: Rebuild all images (recommended)"
echo "cd $PROJECT_DIR/Docker"
echo "docker compose -f docker-compose-emotion.yml build"
echo "docker compose -f docker-compose-mentalstate.yml build"
echo "docker compose -f docker-compose-temperature.yml build"
echo ""
echo "# Option 2: Force rebuild without cache (slower but guarantees fresh build)"
echo "cd $PROJECT_DIR/Docker"
echo "docker compose -f docker-compose-emotion.yml build --no-cache"
echo "docker compose -f docker-compose-mentalstate.yml build --no-cache"
echo "docker compose -f docker-compose-temperature.yml build --no-cache"
echo ""
echo "# Option 3: Use automated build script"
echo "bash $PROJECT_DIR/build_and_test.sh"
echo ""
echo "==============================================="
echo "🧪 TEST EXPERIMENTS"
echo "==============================================="
echo ""
echo "# Quick test (2 rounds, 1 protocol, 1 scenario)"
echo "cd $PROJECT_DIR"
echo "$PYTHON Network_Simulation/run_network_experiments.py --use-case emotion --enable-gpu --single --protocol mqtt --scenario excellent --rounds 2"
echo ""
echo "# Full test all protocols for emotion (2 rounds)"
echo "$PYTHON Network_Simulation/run_network_experiments.py --use-case emotion --enable-gpu --rounds 2"
echo ""
echo "# Full test all 3 use cases (10 rounds, ~6-12 hours)"
echo "for use_case in emotion mentalstate temperature; do"
echo "  $PYTHON Network_Simulation/run_network_experiments.py --use-case \$use_case --enable-gpu --rounds 10"
echo "done"
echo ""
echo "==============================================="
echo "✅ VERIFICATION COMMANDS"
echo "==============================================="
echo ""
echo "# Verify pip installed dependencies in container"
echo "docker exec fl-server-mqtt-emotion pip list | grep -E 'pandas|matplotlib|pytz|dateutil|Pillow'"
echo ""
echo "# Verify imports work in container"
echo "docker exec fl-server-mqtt-emotion python -c \"import pandas; import matplotlib.pyplot; print('✅ All imports successful')\""
echo ""
echo "# Verify GPU detection"
echo "docker exec fl-server-mqtt-emotion python -c \"import tensorflow as tf; print('GPUs:', tf.config.list_physical_devices('GPU'))\""
echo ""
echo "==============================================="
echo "📊 RESULTS LOCATION"
echo "==============================================="
echo ""
echo "Results saved in: $PROJECT_DIR/experiment_results/"
echo "Folder pattern: {use_case}_{YYYYMMDD_HHMMSS}/"
echo ""
echo "==============================================="
